events { worker_connections 1024 }

http {
    # Bizning Backend klasterimiz (Auto-scaling va High-Availability nusxalari)
    upstream erp_backend {
        # Round-Robin algoritmi bo'yicha so'rovlar navbatma-navbat bo'linadi
        server erp_backend_1:5000;
        server erp_backend_2:5000;
        server erp_backend_3:5000;
    }

    server {
        listen 80;

        # Kelayotgan so'rovlarni backend klasteriga yukni bo'lib yuborish
        location / {
            proxy_pass http://erp_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded-for;
        }
    }
}