user  nginx;
worker_processes auto;
error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    # Bizning Backend klasterimiz (Auto-scaling va High-Availability nusxalari)
    # Round-Robin algoritmi bo'yicha so'rovlar navbatma-navbat 3 ta serverga bo'linadi
    upstream app_server {
        server erp_backend_1:5000;
        server erp_backend_2:5000;
        server erp_backend_3:5000;
    }

    server {
        listen 80;
        server_name _;

        # Rasmlar yuklanganda xato bermasligi uchun limitni oshiramiz (AWS S3 ga yuborish uchun)
        client_max_body_size 100M;

        location / {
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   Host $host;
            proxy_set_header   X-NginX-Proxy true;
            
            # Kelayotgan so'rovlarni yuqoridagi 3 ta serverga bo'lib yuboradi
            proxy_pass         http://app_server;
            
            proxy_http_version 1.1;
            proxy_set_header   Connection "";
            proxy_buffering    off;
        }

        # Statik fayllar keshlanishi va so'rovlar klasterga borishi uchun
        location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
            proxy_pass http://app_server;
            expires max;
            add_header Cache-Control "public";
        }
    }
}